### ISSUE TITLE
Java package fails to start in OSX 10.6.8

### ISSUE THREAD

**Issue by JRSV** [monkeyswarm/MobMuPlatEditor#14]
Hello, 

I have used the editor a couple of years ago when you offered a folder named "editor_OSXSnowLeopardAndBelow" this version of the JAVA based app worked, today I wanted to check out the new version, but I get the following error.

> Failed to load Main-Class manifest attribute from /MobMuPlatEditor-master/MobMuPlatEditor-Java/lib/gson-2.2.4.jar

any suggestions to fix this?

**Comment by monkeyswarm** [comment]
What is the command that you run to attempt to start the .jar? Is it
java -jar MobMuPlatEditor.jar
?

**Comment by JRSV** [comment]
there is no "MobMuPlatEditor.jar" when I download the package. There is a Folder called
"MobMuPlatEditor-Java" which contains "lib" and "src". the .jar that you describe is nowhere o be found in either of those folders. BTW, I downloaded the package a couple of times.

**Comment by monkeyswarm** [comment]
You are looking at the source code on github, but you want compiled executables. The compiled applications are distributed via a download link on the front page of www.mobmuplat.com, as described in the README.md

**Comment by JRSV** [comment]
OH, ok, I got confused because it says android and IOS. will give it a go and hopefully it will work, sorry about that.

**Comment by JRSV** [comment]
ok, tried it.. still get an error, this is what my terminal spits out:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/iglesiaintermedia/MobMuPlatEditor/MMPWindow : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

On OSX 10.6.8, I can't update java to this version, as it no longer runs in this system.(http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html#close)

**Comment by monkeyswarm** [comment]
http://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi

**Comment by monkeyswarm** [comment]
The error is for java 7, let me check why I used java 7
